# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc2824f42d39872ae98e2b100b158a7c2d108ef77057bd3affdac33b3d55648af4bd3925d6833327942f1b0554f443de1d5ddd195ddac43ac8dad9d6e2c0dc47

test:
  secret_key_base: 727872dcf2bf7b14e08bf7f8d7998ced1f75ab0ce51f6bb17dd8cef1f3312dbdc3c0fb68c57dcb5211216ae367646b65ae234b7972b8c0cdcb8737b8a3b1f37f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
